### ISSUE TITLE
AspectJ Internal Error: Unsupported class file major version 61

### ISSUE THREAD

**Issue by ptziegler** [eclipse/org.eclipse.rcptt#19]
I'm currently preparing our product for the upcoming Eclipse release, which requires at least Java 17. RCPTT is currently using AspectJ 1.9.7, which only supports Java versions up to [15/16](https://github.com/eclipse-aspectj/aspectj/blob/master/docs/dist/doc/JavaVersionCompatibility.md), making it impossible to launch our application.

This version of AspectJ is contributed by AJDT up to version 421. RCPTT is currently still using 410. Is it possible to update this dependency?

**Comment by basilevs** [comment]
Sure, we accept PRs. AFAIK, the dependency is fetched in https://github.com/eclipse/org.eclipse.rcptt/blob/8b471e9b7aca756dcd4f42c786af032c8426e8e8/dependencies/bundles/org.eclipse.rcptt.updates.aspectj.e44x/pom.xml#L56 but I may be wrong.

**Comment by ptziegler** [comment]
The problem seems to already be solved as part of #2, so I'm not sure if it makes sense to create a separate pull request with effectively the same change.
I tried building/testing the branch locally and so far without any issues. Is there anything else holding back the branch from being merged?

**Comment by benken-parasoft** [comment]
> Is there anything else holding back the branch from being merged?

Any update?  This is blocking us from testing AUT with Eclipse 4.8 and Java 17.

**Comment by basilevs** [comment]
The builds in #2 are failing for reasons unrelated to the change, so we can't merge that.

**Comment by basilevs** [comment]
I've recreated #2 as #24 in hope, that build failures are caused by Jenkins sticky state.
