### ISSUE TITLE
Broken download link

### ISSUE THREAD

**Issue by jochenberger** [eclipse/org.eclipse.rcptt#25]
The nightly runner download link on https://eclipse.dev/rcptt/download/ is broken, it points to http://download.eclipse.org/rcptt/nightly///runner/rcptt.runner--N.zip

**Comment by basilevs** [comment]
Commented in https://gitlab.eclipse.org/eclipsefdn/it/websites/eclipse.org/-/issues/376

**Comment by basilevs** [comment]
The issue is fixed on hosting side. The links are accurate again.
