### ISSUE TITLE
Please release

### ISSUE THREAD

**Issue by Mailaender** [eclipse/org.eclipse.rcptt#35]
Hi, can you tag `2.5.5`, please? The nightly already supports Eclipse `2023-06` which `2.5.4` does not.

**Comment by basilevs** [comment]
While we don't have manpower to do this, I've checked and found that https://wiki.eclipse.org/RCPTT/Release_procedure is blocked by Jenkins configuration corrupted due to migration to GIthub. I've changed https://ci.eclipse.org/rcptt/view/active/job/Pull_requests/ to look for branches, in hope that we could test the release branch that way.

**Comment by basilevs** [comment]
I'm working on release 2.5.5 now.

**Comment by basilevs** [comment]
@Mailaender I've published a milsetone https://repo.eclipse.org/content/repositories/rcptt-releases/org/eclipse/rcptt/rcptt-maven-plugin/2.5.5-MO/ (note a typo in milestone number)./705abd5558b37b8039f7edc30a2e6c9ba95484f4
It should contain your changes for platform 2023-06.

**Comment by Mailaender** [comment]
I tested the IDE and the runner on Linux. Works fine, and themeing issues seem to be gone now!

**Comment by basilevs** [comment]
2.5.5-M3 is deployed. This is release candidate. The outstanding problem is consistent AUT shutdown during long testsuite. It will not be fixed in this release.

**Comment by basilevs** [comment]
I've published RCPTT 2.5.5 the consequences may be dire, as no significant verification was done. Good luck.

**Comment by Mailaender** [comment]
The release indeed does not work
> AUT-0: Launch failed. Reason: FAIL: AUT requires x86_64 Java VM which cannot be found.
Please specify -autVM {javaPath} command line argument to use different JVM.

I had to revert to `rcptt.runner-2.5.5-M1`.

**Comment by basilevs** [comment]
Version bump is stuck, as [builds are failing](https://ci.eclipse.org/rcptt/view/active/job/Pull_requests/job/master/94/console) due to [#4980](https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4980)
