### ISSUE TITLE
Two items are logged with log command

### ISSUE THREAD

**Issue by ulikcuc** [eclipse/org.eclipse.rcptt#44]
RCPTT test fails: ColumnTitleClick

clear-log-view 
log string1
log string2
log string3

Actual:

<img width="660" alt="Screenshot 2024-03-18 at 21 02 21" src="https://github.com/eclipse/org.eclipse.rcptt/assets/2705175/729dfd34-1d8f-44d8-ba18-869b7d95c078">

**Comment by ulikcuc** [comment]
workaround: use wait 1000 between log commands

**Comment by basilevs** [comment]
Another workaround is to use any UI command between log commands. Done in https://github.com/eclipse/org.eclipse.rcptt/commit/1423b3c516b31c80fef69a3c07e22024ee7b1172

This is a defect in Error Log view, so we are not going to fix it.
