### ISSUE TITLE
Frequently seeing Failed to apply context clear.ctx (Clear workspace context)

### ISSUE THREAD

**Issue by sramshek** [eclipse/org.eclipse.rcptt#70]
Hey @basilevs , We have been seeing this error (when trying to apply Clear Workspace context) intermittently in our daily automation tests. This does not always happens and never happens because of same reasons.

`Failed to apply context clear.ctx: Failed to apply context "clear" caused by: Possible resource leak in AUT. Files below are locked and cannot be deleted:`

I can understand that some processes or file might have been locked when the clear.ctx is applied, but we try to kill all the processes as startup clean-up, however, some processes might have left hanging.  since it is not reproduced because of same reasons everytime, it becomes tough to narrow it down.

Is there a way we can handle this in some other way ? or may be not fail the context (some sort of try -catch mechanism,) ? or is there a way to apply this context in ECL commands/script ?

**Comment by basilevs** [comment]
This is Windows specific behavior - opened files can't be deleted.

1. Monitor your applications with resource managers like [Sysinternals Process Explorer](https://serverfault.com/questions/1966/how-do-you-find-what-process-is-holding-a-file-open-in-windows), to find out which scenario fails to close a file.
2. Run tests on Linux - filesystem locks there do not prevent file deletion.
3. Remember, files could be opened by AUT itself, not necessarily by another application. Add ECL context before Workspace context to cleanup state of AUT before file are to be deleted. 

RCPTT itself won't be able to help - a failure to reset workspace would cause instability of tests.
