### ISSUE TITLE
New RCPTT Version ?

### ISSUE THREAD

**Issue by sramshek** [eclipse/org.eclipse.rcptt#81]
Hi,
Is there any plan to release new RCPTT version , specifically which supports Java21+ ?

**Comment by Mailaender** [comment]
Try the https://download.eclipse.org/rcptt/milestone/2.5.5/

**Comment by Mailaender** [comment]
Duplicate of https://github.com/eclipse/org.eclipse.rcptt/issues/35

**Comment by sramshek** [comment]
Thanks
