### ISSUE TITLE
News for updates around java21 and Eclipse 2024-06

### ISSUE THREAD

**Issue by christelleburguera** [eclipse/org.eclipse.rcptt#82]
Hello,

What are your plans around the updates to support java21 and Eclipse 2024-06 ?
thank you so much for your answer, @basilevs :)

Have a very nice day
Christelle

**Comment by basilevs** [comment]
I think they are supported in RCPTT 2.5.5-M3. Please report otherwise.
Closing as duplicate of https://github.com/eclipse/org.eclipse.rcptt/issues/35

**Comment by christelleburguera** [comment]
thank you, we'll try :)
have a good day

**Comment by basilevs** [comment]
> I try to have news about your plans around 202**4**-06 and java21

Please report if 2024-06 and Java 21 are producing bugs in 2.5.5-M3. This is a duplicate, because the support has not reached released RCPTT. (RCPTT 2.5.4 does not support latest platforms)
