### ISSUE TITLE
Non compatibility between  Eclipse native 2024. RCPTT 2.5.5-N202407061358 -06

### ISSUE THREAD

**Issue by nadasmat** [eclipse/org.eclipse.rcptt#89]
We have faced an issue with non compatibility between  Eclipse native 2024. RCPTT 2.5.5-N202407061358 -06. Is there a new RCPTT version in perspective to ensure such compatibility. If yes, when is it planned ? 
@basilevs do you have an idea about the topic

**Comment by basilevs** [comment]
RCPTT installs into Eclipse Version: 2024-06 (4.32) Build id: I20240601-0610 and starts self-AUT. Please update the report to include the test steps, expected and actual results.

**Comment by nadasmat** [comment]
Hello @basilevs 
 I attach the log file 
[RCPTT.txt](https://github.com/user-attachments/files/16614968/RCPTT.txt)

**Comment by basilevs** [comment]
This is IDE log. It is not useful. Consider inspecting AUT's log instead.

**Comment by nadasmat** [comment]
Test redone with the version 2.5.5.202408251355. Seem to work just fine
