### ISSUE TITLE
Black screen display blocking RCPTT test execution

### ISSUE THREAD

**Issue by KhouloudHD** [eclipse/org.eclipse.rcptt#93]
We're having problems with our automation script, as we're using Mac Sonoma:
black screen display which prevents the execution of our automated tests with RCPTT. 
Environment used:
MacSonoma 14.6
RCPTT 2.5.5-N202409011355
Logiciel: STM32CubeIDE 1.16.0
<img width="604" alt="attachement1" src="https://github.com/user-attachments/assets/2c098783-2152-4ab3-80ec-62e158ce1c91">

**Comment by basilevs** [comment]
This is likely caused by disabled graphical context. Disable automatic logout, power-saving features, configure automatic login. Also, try launching stadalone Eclipse in the same context and schdule taking of screenshots, ensure that standalone Eclipse does not suffer same symptoms
